name: build Pages
on:
  push:
    branches:
      - main
    paths:
      - "*.md"
      - docs/**
      - .github/workflows/pages.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3

      - name: Install Dependences
        run: |
          pip install pdm
          pdm install -dG docs

      - name: Build Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # git fetch origin gh-pages:gh-pages
          pdm run mkdocs gh-deploy
          git push origin gh-pages